### ISSUE TITLE
Crop+Compress+Reduce length of gif?

### ISSUE THREAD

**Issue by usernamehw** [nexes/statusbar-error#2]
That's some nice **15.4Mb** `.gif` you got there...

**Comment by nexes** [comment]
Updated with new gif with smaller size. The quality of the new one is not great, may update it but it's low priority.

**Comment by usernamehw** [comment]
@nexes There's surely some good `.gif` recording software for mac. I thought recommending this app https://github.com/NickeManarin/ScreenToGif, but it seems to be `Windows` only. Maybe you can use the one that I just made?

![demo_status_bar](https://user-images.githubusercontent.com/9638156/52386481-5b32e080-2a97-11e9-87d5-ed2e55cb7281.gif)
