### ISSUE TITLE
Show Error In JSON Files

### ISSUE THREAD

**Issue by fakhamatia** [nexes/statusbar-error#3]
hi
in JSON files showing the error its not real time :

![Image](http://uupload.ir/files/a3a2_idm.gif)

i test it in HTML PHP JS its working 
VSCode 1.31.1 , Extensions 0.3.0

**Comment by nexes** [comment]
I have not been able to reproduce this issue. JSON files works for me like all other files. If you write your own json file to test with, does it happen with that? Or with a npm package.json file?

**Comment by nexes** [comment]
not able to reproduce, closing issue due to lack of response. Please re-open issue if it happens again and you have reproducible steps.
