### ISSUE TITLE
[Feature] disable for certain error type 

### ISSUE THREAD

**Issue by ctf0** [nexes/statusbar-error#4]
many thanx for the gutter error icons, i was wondering if its possible to disable it for certain types ex.info/hint errors ?

**Comment by nexes** [comment]
That's a good idea. I should be able to get that setup and an update out this weekend.

**Comment by ctf0** [comment]
if also applicable, can u truncate the inline error msg, as atm with large text, the editor starts to freeze

**Comment by nexes** [comment]
c15b2dc762ea21c2b112108d94bc0a6e66260029 you can now set a max length to the linter messages for the whole line. 

569588c7c2db98fc0148b378995035451cce72b6 now you can toggle certain gutter icons on or off.
