### ISSUE TITLE
why '?' is so big

### ISSUE THREAD

**Issue by youngnet** [nexes/statusbar-error#5]
![image](https://user-images.githubusercontent.com/22018085/57498523-c26a6600-730e-11e9-84cd-fb475bf0d234.png)

**Comment by nexes** [comment]
I'll be able to fix that and get an update out this weekend.

**Comment by nexes** [comment]
3238b3854fac44721ea2ca4288ba22b1b200f2d8 changed svg size for the info icon in the gutter. closing issue.
