### ISSUE TITLE
Add option to disable showing error on status bar

### ISSUE THREAD

**Issue by FatehAK** [nexes/statusbar-error#6]
Can you add an option to disable showing errors in status bar? I know there is an option to disable line and gutter errors but there is no option to disable status bar errors...

**Comment by nexes** [comment]
Sure, I'm planning on getting an update out sometime this weekend, I can add that option.

**Comment by nexes** [comment]
9103d96dfc3c3b009eb3dc072c2ed75b877a7bdb can now disable the message in the statusbar. Closing issue.
